In [6]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

from cv02504.util_functions import *

In [7]:
# Q1: camera intrinsic matrix
K = camera_intrinsic(1200, (400,350), alpha=1, beta=0)
K

array([[1200,    0,  400],
       [   0, 1200,  350],
       [   0,    0,    1]])

In [8]:
# Q2: resizing image
Px = 0.4
print(Px*1000+400)
print(Px*500+200)

800.0
400.0


In [9]:
# Q3: projection
K = camera_intrinsic(1720, (680,610), 1, 0)
R = cv2.Rodrigues(np.array([-0.1, 0.1, -0.2]))[0]
t = np.array([[0.09], [0.05], [0.05]])
Q = np.array([[-0.03, 0.01, 0.59]]).T

print(Q.shape)

ans = project_points(K, R, t, Q)
ans

(3, 1)


array([[1023.50377104],
       [ 930.29756751]])

In [10]:
Rt = np.hstack((R, t))
ph = Pi(K @ Rt @ PiInv(Q))
ph

array([[1023.50377104],
       [ 930.29756751]])

In [11]:
# Q5: epipolar line
K = np.array([[900, 0, 1070], [0, 900, 610.0], [0, 0, 1]], float)
R1 = cv2.Rodrigues(np.array([-1.6, 0.3, -2.1]))[0]
t1 = np.array([[0.0], [1.0], [3.0]], float)
R2 = cv2.Rodrigues(np.array([-0.4, -1.3, -1.6]))[0]
t2 = np.array([[0.0], [1.0], [6.0]], float)
R3 = cv2.Rodrigues(np.array([2.5, 1.7, -0.4]))[0]
t3 = np.array([[2.0], [-7.0], [25.0]], float)

p1 = np.array([[1046.0], [453.0]])  # 2x1
p2 = np.array([[1126.0], [671.0]])
p3 = np.array([[1165.0], [453.0]])

F = fundamental_matrix(K, R1, t1, K, R2, t2)

epiline_c2 = F @ PiInv(p1)
dist = epiline_c2.T @ PiInv(p2)
dist

array([[-0.0931562]])

In [12]:
# Q6: triangulation without normalization
P1 = K @ np.hstack((R1, t1))
P2 = K @ np.hstack((R2, t2))
P3 = K @ np.hstack((R3, t3))

q1 = PiInv(p1)
q2 = PiInv(p2)
q3 = PiInv(p3)

Q = triangulate([q1, q2, q3], [P1, P2, P3])
Q

array([[3.10058867],
       [0.74321098],
       [0.46490561]])