In [4]:
import numpy as np
import cv2

In [ ]:
# Q1
def point_line_distance(line, p):
    """
    Calculate shortest distance d between line l
    and 2D homogenous point p.

    e.g.
    line = np.array([1,0,1])
    p = np.array([0,0,1])
    """
    d = abs(line @ p) / (abs(p[2]) * np.sqrt(line[0] ** 2 + line[1] ** 2))
    return d


q = np.array([2, 4, 3]).T
line = np.array([1, 2, 2]).T
point_line_distance(line, q)

2.3851391759997758

In [10]:
# Q2
def Pi(ph):
    """
    Converts coordinates from homogeneous to inhomogeneous.
    ph : 4xn np.array
    p : 3xn np.array
    """
    p = ph[:-1] / ph[-1]  # divide by and remove last coordinate
    return p


def PiInv(p):
    """
    Converts coordinates from inhomogeneous to homogeneous.
    p : 3xn np.array
    ph : 4xn np.array
    """
    ph = np.vstack((p, np.ones(p.shape[1])))
    return ph


# pose
R = cv2.Rodrigues(np.array([-0.1, 0.1, -0.2]))[0]
t = np.array([[0.09], [0.05], [0.05]])

Q = np.array([-0.03, 0.01, 0.59])
Q = Q.reshape(-1, 1)
print("Q:", Q.shape)

# camera intrinsics
f = 1720
pp = (680, 610.0)
K = np.array([[f, 0, pp[0]], [0, f, pp[1]], [0, 0, 1]])

# projection onto image plane
Qh = PiInv(Q)  # 4 x 1
print(Qh)
pose = np.hstack((R, t))  # 3 x 4
print(pose)
Ph = K @ pose @ Qh  # 3 x 1
print(Ph)
P = Pi(Ph)  # 2 x 1
P

Q: (3, 1)
[[-0.03]
 [ 0.01]
 [ 0.59]
 [ 1.  ]]
[[ 0.97512475  0.19303094  0.1089531   0.09      ]
 [-0.20298104  0.97512475  0.0890529   0.05      ]
 [-0.0890529  -0.1089531   0.9900499   0.05      ]]
[[6.50653114e+02]
 [5.91400859e+02]
 [6.35711497e-01]]


array([[1023.50377104],
       [ 930.29756751]])

In [7]:
# from Copilot

import numpy as np


def project_3d_point_to_2d(
    point_3d, focal_length, principal_point, rotation_matrix, translation_vector
):
    # Create the camera intrinsic matrix
    intrinsic_matrix = np.array(
        [
            [focal_length, 0, principal_point[0]],
            [0, focal_length, principal_point[1]],
            [0, 0, 1],
        ]
    )

    # Create the camera extrinsic matrix
    extrinsic_matrix = np.hstack((rotation_matrix, translation_vector))

    # Create the camera projection matrix
    projection_matrix = np.dot(intrinsic_matrix, extrinsic_matrix)

    # Append a 1 to the 3D point to create a homogeneous coordinate
    point_3d_homogeneous = np.append(point_3d, 1)

    # Project the 3D point to 2D
    point_2d_homogeneous = np.dot(projection_matrix, point_3d_homogeneous)

    # Convert the 2D point from homogeneous to Cartesian coordinates
    point_2d = point_2d_homogeneous[:2] / point_2d_homogeneous[2]

    return point_2d


ans = project_3d_point_to_2d(Q, f, pp, R, t)
ans

array([3215.06394671,  930.29756751])